version: '3.8'

services:
  web:
    image: facedeetection:latest  # Add this line to use existing image
    build: .
    ports:
      - "5000:5001"
    environment:
      - AWS_REGION=eu-west-3
      - COGNITO_USER_POOL_ID=eu-west-3_H1UTyevos
      - COGNITO_CLIENT_ID=6pv9g6ad1b0fhfo06v8g9b0alm
      - COGNITO_CLIENT_SECRET=1eudob0bpbieaus6q2edmd3qrahuj65ldd8562rccck6dtbhu4rd
      - MONGO_URI=mongodb://mongo:27017
      - EUREKA_SERVER=http://discovery-service:8761/eureka
      - STUDENT_SERVICE_URL=http://student-service:8082
    networks:
      - class-network
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27018"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
networks:
  class-network: